import {transactionLocalDataSource} from '@/src/Z_SRC/data/local/transactions/transactionLocalDataSource';
import {now} from '@/src/Z_SRC/core/date/now';

export async function seedTransactions2026() {
  await transactionLocalDataSource.insertMany([
    // January 2026
    {
      id: 'txn_2026_01_salary',
      type: 'income',
      amount: 1850000,
      currency: 'ARS',
      amount_in_main_currency: 1850000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-01-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_supermarket_01',
      type: 'expense',
      amount: 86500,
      currency: 'ARS',
      amount_in_main_currency: 86500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-01-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_food_01',
      type: 'expense',
      amount: 18200,
      currency: 'ARS',
      amount_in_main_currency: 18200,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_food',
      occurred_at: '2026-01-09T21:00:00.000Z',
      note: 'Dinner',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_house',
      type: 'expense',
      amount: 145000,
      currency: 'ARS',
      amount_in_main_currency: 145000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-01-10T10:00:00.000Z',
      note: 'House expenses',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_transport',
      type: 'expense',
      amount: 21500,
      currency: 'ARS',
      amount_in_main_currency: 21500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_transport',
      occurred_at: '2026-01-14T09:30:00.000Z',
      note: 'Transport',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_car',
      type: 'expense',
      amount: 98000,
      currency: 'ARS',
      amount_in_main_currency: 98000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_car',
      occurred_at: '2026-01-18T15:00:00.000Z',
      note: 'Car maintenance',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_01_usd_savings',
      type: 'income',
      amount: 150,
      currency: 'USD',
      amount_in_main_currency: 157500,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_savings',
      occurred_at: '2026-01-20T12:00:00.000Z',
      note: 'USD savings',
      exchange_rate_to_main_currency: 1050,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // February 2026
    {
      id: 'txn_2026_02_salary',
      type: 'income',
      amount: 1900000,
      currency: 'ARS',
      amount_in_main_currency: 1900000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-02-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_02_supermarket_01',
      type: 'expense',
      amount: 92400,
      currency: 'ARS',
      amount_in_main_currency: 92400,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-02-06T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_02_services',
      type: 'expense',
      amount: 76000,
      currency: 'ARS',
      amount_in_main_currency: 76000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_services',
      occurred_at: '2026-02-08T10:00:00.000Z',
      note: 'Services',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_02_food',
      type: 'expense',
      amount: 23600,
      currency: 'ARS',
      amount_in_main_currency: 23600,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_food',
      occurred_at: '2026-02-12T21:00:00.000Z',
      note: 'Restaurant',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_02_health',
      type: 'expense',
      amount: 64500,
      currency: 'ARS',
      amount_in_main_currency: 64500,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_health',
      occurred_at: '2026-02-17T13:15:00.000Z',
      note: 'Health',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_02_shopping',
      type: 'expense',
      amount: 132000,
      currency: 'ARS',
      amount_in_main_currency: 132000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_shopping',
      occurred_at: '2026-02-22T17:45:00.000Z',
      note: 'Shopping',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // March 2026
    {
      id: 'txn_2026_03_salary',
      type: 'income',
      amount: 1950000,
      currency: 'ARS',
      amount_in_main_currency: 1950000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-03-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_03_supermarket',
      type: 'expense',
      amount: 101000,
      currency: 'ARS',
      amount_in_main_currency: 101000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-03-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_03_transport',
      type: 'expense',
      amount: 27500,
      currency: 'ARS',
      amount_in_main_currency: 27500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_transport',
      occurred_at: '2026-03-08T09:30:00.000Z',
      note: 'Transport',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_03_house',
      type: 'expense',
      amount: 168000,
      currency: 'ARS',
      amount_in_main_currency: 168000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-03-10T10:00:00.000Z',
      note: 'House expenses',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_03_car',
      type: 'expense',
      amount: 117000,
      currency: 'ARS',
      amount_in_main_currency: 117000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_car',
      occurred_at: '2026-03-18T15:00:00.000Z',
      note: 'Fuel and car',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_03_usd_travel',
      type: 'expense',
      amount: 90,
      currency: 'USD',
      amount_in_main_currency: 99000,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_travel',
      occurred_at: '2026-03-24T16:00:00.000Z',
      note: 'Travel USD',
      exchange_rate_to_main_currency: 1100,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // April 2026
    {
      id: 'txn_2026_04_salary',
      type: 'income',
      amount: 2050000,
      currency: 'ARS',
      amount_in_main_currency: 2050000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-04-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_04_supermarket',
      type: 'expense',
      amount: 112000,
      currency: 'ARS',
      amount_in_main_currency: 112000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-04-05T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_04_food',
      type: 'expense',
      amount: 28500,
      currency: 'ARS',
      amount_in_main_currency: 28500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_food',
      occurred_at: '2026-04-11T21:00:00.000Z',
      note: 'Food',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_04_services',
      type: 'expense',
      amount: 89500,
      currency: 'ARS',
      amount_in_main_currency: 89500,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_services',
      occurred_at: '2026-04-12T10:00:00.000Z',
      note: 'Services',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_04_shopping',
      type: 'expense',
      amount: 154000,
      currency: 'ARS',
      amount_in_main_currency: 154000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_shopping',
      occurred_at: '2026-04-19T17:45:00.000Z',
      note: 'Shopping',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_04_extra_income',
      type: 'income',
      amount: 135000,
      currency: 'ARS',
      amount_in_main_currency: 135000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_earnings',
      occurred_at: '2026-04-26T12:00:00.000Z',
      note: 'Extra income',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // May 2026
    {
      id: 'txn_2026_05_salary',
      type: 'income',
      amount: 2150000,
      currency: 'ARS',
      amount_in_main_currency: 2150000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_salary',
      occurred_at: '2026-05-03T12:00:00.000Z',
      note: 'Monthly salary',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_05_supermarket',
      type: 'expense',
      amount: 121000,
      currency: 'ARS',
      amount_in_main_currency: 121000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-05-06T18:20:00.000Z',
      note: 'Supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_05_house',
      type: 'expense',
      amount: 188000,
      currency: 'ARS',
      amount_in_main_currency: 188000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-05-10T10:00:00.000Z',
      note: 'House expenses',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_05_transport',
      type: 'expense',
      amount: 31500,
      currency: 'ARS',
      amount_in_main_currency: 31500,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_transport',
      occurred_at: '2026-05-14T09:30:00.000Z',
      note: 'Transport',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_05_health',
      type: 'expense',
      amount: 79000,
      currency: 'ARS',
      amount_in_main_currency: 79000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_health',
      occurred_at: '2026-05-18T13:15:00.000Z',
      note: 'Health',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_05_usd_savings',
      type: 'income',
      amount: 200,
      currency: 'USD',
      amount_in_main_currency: 230000,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_savings',
      occurred_at: '2026-05-22T12:00:00.000Z',
      note: 'USD savings',
      exchange_rate_to_main_currency: 1150,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // Random extra transactions before June 2026
    {
      id: 'txn_2026_random_001',
      type: 'expense',
      amount: 42000,
      currency: 'ARS',
      amount_in_main_currency: 42000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_food',
      occurred_at: '2026-01-23T21:15:00.000Z',
      note: 'Dinner with friends',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_002',
      type: 'expense',
      amount: 73500,
      currency: 'ARS',
      amount_in_main_currency: 73500,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_services',
      occurred_at: '2026-01-27T11:30:00.000Z',
      note: 'Internet and phone',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_003',
      type: 'expense',
      amount: 112000,
      currency: 'ARS',
      amount_in_main_currency: 112000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_health',
      occurred_at: '2026-01-29T16:45:00.000Z',
      note: 'Medical appointment',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    {
      id: 'txn_2026_random_004',
      type: 'expense',
      amount: 58000,
      currency: 'ARS',
      amount_in_main_currency: 58000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_transport',
      occurred_at: '2026-02-03T08:20:00.000Z',
      note: 'Transport pass',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_005',
      type: 'expense',
      amount: 215000,
      currency: 'ARS',
      amount_in_main_currency: 215000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_shopping',
      occurred_at: '2026-02-11T18:10:00.000Z',
      note: 'Clothes',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_006',
      type: 'expense',
      amount: 97000,
      currency: 'ARS',
      amount_in_main_currency: 97000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-02-19T10:00:00.000Z',
      note: 'Home supplies',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_007',
      type: 'income',
      amount: 95000,
      currency: 'ARS',
      amount_in_main_currency: 95000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_deposits',
      occurred_at: '2026-02-25T14:00:00.000Z',
      note: 'Cash deposit',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    {
      id: 'txn_2026_random_008',
      type: 'expense',
      amount: 65000,
      currency: 'ARS',
      amount_in_main_currency: 65000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-03-02T19:30:00.000Z',
      note: 'Small supermarket',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_009',
      type: 'expense',
      amount: 186000,
      currency: 'ARS',
      amount_in_main_currency: 186000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_travel',
      occurred_at: '2026-03-12T17:20:00.000Z',
      note: 'Weekend trip',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_010',
      type: 'expense',
      amount: 52000,
      currency: 'ARS',
      amount_in_main_currency: 52000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_food',
      occurred_at: '2026-03-16T22:10:00.000Z',
      note: 'Restaurant',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_011',
      type: 'expense',
      amount: 43000,
      currency: 'ARS',
      amount_in_main_currency: 43000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_car',
      occurred_at: '2026-03-21T15:40:00.000Z',
      note: 'Fuel',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_012',
      type: 'income',
      amount: 120000,
      currency: 'ARS',
      amount_in_main_currency: 120000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_earnings',
      occurred_at: '2026-03-28T13:00:00.000Z',
      note: 'Freelance payment',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    {
      id: 'txn_2026_random_013',
      type: 'expense',
      amount: 138000,
      currency: 'ARS',
      amount_in_main_currency: 138000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_health',
      occurred_at: '2026-04-02T12:30:00.000Z',
      note: 'Health insurance',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_014',
      type: 'expense',
      amount: 72000,
      currency: 'ARS',
      amount_in_main_currency: 72000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_transport',
      occurred_at: '2026-04-07T09:10:00.000Z',
      note: 'Transport',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_015',
      type: 'expense',
      amount: 164000,
      currency: 'ARS',
      amount_in_main_currency: 164000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_shopping',
      occurred_at: '2026-04-14T18:45:00.000Z',
      note: 'Tech accessories',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_016',
      type: 'expense',
      amount: 245,
      currency: 'USD',
      amount_in_main_currency: 281750,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_travel',
      occurred_at: '2026-04-18T20:00:00.000Z',
      note: 'Hotel reservation',
      exchange_rate_to_main_currency: 1150,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_017',
      type: 'income',
      amount: 180,
      currency: 'USD',
      amount_in_main_currency: 207000,
      main_currency: 'ARS',
      account_id: 'acc_cash_usd',
      category_id: 'cat_savings',
      occurred_at: '2026-04-27T12:00:00.000Z',
      note: 'USD savings',
      exchange_rate_to_main_currency: 1150,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    {
      id: 'txn_2026_random_018',
      type: 'expense',
      amount: 91000,
      currency: 'ARS',
      amount_in_main_currency: 91000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_supermarket',
      occurred_at: '2026-05-01T19:20:00.000Z',
      note: 'Groceries',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_019',
      type: 'expense',
      amount: 124000,
      currency: 'ARS',
      amount_in_main_currency: 124000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_services',
      occurred_at: '2026-05-08T10:30:00.000Z',
      note: 'Utilities',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_020',
      type: 'expense',
      amount: 255000,
      currency: 'ARS',
      amount_in_main_currency: 255000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_mastercard',
      category_id: 'cat_travel',
      occurred_at: '2026-05-13T16:25:00.000Z',
      note: 'Flight tickets',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_021',
      type: 'expense',
      amount: 68000,
      currency: 'ARS',
      amount_in_main_currency: 68000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_food',
      occurred_at: '2026-05-19T21:35:00.000Z',
      note: 'Dinner',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_022',
      type: 'expense',
      amount: 152000,
      currency: 'ARS',
      amount_in_main_currency: 152000,
      main_currency: 'ARS',
      account_id: 'acc_bbva_visa',
      category_id: 'cat_house',
      occurred_at: '2026-05-24T11:00:00.000Z',
      note: 'Home repair',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'txn_2026_random_023',
      type: 'income',
      amount: 165000,
      currency: 'ARS',
      amount_in_main_currency: 165000,
      main_currency: 'ARS',
      account_id: 'acc_cash_ars',
      category_id: 'cat_daily_performance',
      occurred_at: '2026-05-29T12:00:00.000Z',
      note: 'Daily performance',
      exchange_rate_to_main_currency: 1,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
  ]);
}
