import {categoryLocalDataSource} from '@/src/Z_SRC/data/local/categories/categoryLocalDataSource';
import {now} from '@/src/Z_SRC/core/date/now';

export async function seedDefaultCategories() {
  const count = await categoryLocalDataSource.count();

  if (count > 0) return;

  await categoryLocalDataSource.insertMany([
    // Expenses
    {
      id: 'cat_food',
      name: 'Food',
      type: 'expense',
      icon: 'restaurant',
      color: '#22C55E',
      background_color: 'rgba(34, 197, 94, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_supermarket',
      name: 'Supermarket',
      type: 'expense',
      icon: 'shoppingCart',
      color: '#16A34A',
      background_color: 'rgba(22, 163, 74, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_house',
      name: 'House',
      type: 'expense',
      icon: 'home',
      color: '#F59E0B',
      background_color: 'rgba(245, 158, 11, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_transport',
      name: 'Transport',
      type: 'expense',
      icon: 'bus',
      color: '#3B82F6',
      background_color: 'rgba(59, 130, 246, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_car',
      name: 'Car',
      type: 'expense',
      icon: 'car',
      color: '#2563EB',
      background_color: 'rgba(37, 99, 235, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_shopping',
      name: 'Shopping',
      type: 'expense',
      icon: 'shoppingBag',
      color: '#FB7185',
      background_color: 'rgba(251, 113, 133, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_health',
      name: 'Health',
      type: 'expense',
      icon: 'heart',
      color: '#EC4899',
      background_color: 'rgba(236, 72, 153, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_services',
      name: 'Services',
      type: 'expense',
      icon: 'tools',
      color: '#64748B',
      background_color: 'rgba(100, 116, 139, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_travel',
      name: 'Travel',
      type: 'expense',
      icon: 'map',
      color: '#06B6D4',
      background_color: 'rgba(6, 182, 212, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },

    // Income
    {
      id: 'cat_salary',
      name: 'Salary',
      type: 'income',
      icon: 'briefcase',
      color: '#10B981',
      background_color: 'rgba(16, 185, 129, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_savings',
      name: 'Savings',
      type: 'income',
      icon: 'wallet',
      color: '#84CC16',
      background_color: 'rgba(132, 204, 22, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_deposits',
      name: 'Deposits',
      type: 'income',
      icon: 'deposit',
      color: '#14B8A6',
      background_color: 'rgba(20, 184, 166, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_daily_performance',
      name: 'Daily performance',
      type: 'income',
      icon: 'chartUp',
      color: '#0EA5E9',
      background_color: 'rgba(14, 165, 233, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
    {
      id: 'cat_earnings',
      name: 'Earnings',
      type: 'income',
      icon: 'moneyReceive',
      color: '#6366F1',
      background_color: 'rgba(99, 102, 241, 0.16)',
      archived_at: null,
      created_at: now(),
      updated_at: now(),
      deleted_at: null,
    },
  ]);
}
